export const papers = [
 {id:1, short:'Principled Instructions', title:'Principled Instructions Are All You Need for Questioning LLaMA-1/2, GPT-3.5/4', authors:'Bsharat, Myrzakhan & Shen', year:'2024 revision · preprint', kind:'Model experiments', url:'https://arxiv.org/html/2312.16171v2', finding:'Studies 26 prompting principles, including explicit requirements and examples, on selected LLaMA and GPT models.', limit:'Results are specific to the models and benchmark. They motivate our curriculum; they do not validate this game.'},
 {id:2, short:'The Prompt Report', title:'The Prompt Report: A Systematic Survey of Prompt Engineering Techniques', authors:'Schulhoff et al.', year:'2025 revision · v6', kind:'Research synthesis', url:'https://arxiv.org/html/2406.06608v6', finding:'Identifies additional information, examples, and output formatting among the components of a prompt.', limit:'A taxonomy supports content selection, not a causal claim that an information-sharing level improves learning.'},
 {id:3, short:'Few-Shot Learners', title:'Language Models are Few-Shot Learners', authors:'Brown et al.', year:'2020 · NeurIPS', kind:'Model experiments', url:'https://papers.neurips.cc/paper/2020/hash/1457c0d6bfcb4967418bfb8ac142f64a-Abstract.html', finding:'Studies how GPT-3 performs tasks using examples supplied in context, without updating model weights.', limit:'Examples are a useful option, not a guarantee of improvement on every task or model.'},
 {id:4, short:'Why Johnny Can’t Prompt', title:'Why Johnny Can’t Prompt: How Non-AI Experts Try (and Fail) to Design LLM Prompts', authors:'Zamfirescu-Pereira et al.', year:'2023 · CHI', kind:'User study · 10 participants', url:'https://people.eecs.berkeley.edu/~bjoern/papers/zamfirescu-johnny-chi2023.pdf', finding:'Observed limited use of examples, opportunistic testing, and overgeneralization from a small number of prompt outcomes.', limit:'The study involved chatbot design with an earlier model. Our new-map exercise is a design response, not the tested intervention.'},
 {id:5, short:'Metacognitive Demands', title:'The Metacognitive Demands and Opportunities of Generative AI', authors:'Tankelevitch et al.', year:'2024 · CHI', kind:'Theory and design framework', url:'https://www.microsoft.com/en-us/research/publication/the-metacognitive-demands-and-opportunities-of-generative-ai/', finding:'Connects goal formulation, output evaluation, confidence, and strategy adjustment in generative AI use.', limit:'Provides an overarching framework. It is not direct evidence for our private-briefing task or six-level sequence.'},
 {id:6, short:'AI Chains', title:'AI Chains: Transparent and Controllable Human-AI Interaction by Chaining Large Language Model Prompts', authors:'Wu, Terry & Cai', year:'2022 · CHI', kind:'User study · 20 participants', url:'https://arxiv.org/abs/2110.01691', finding:'Editable chains improved outcomes and perceived transparency, control, and collaboration in the studied tasks.', limit:'Our approval checkpoint is an application of this work, not a finding about a specific approval phrase.'},
 {id:7, short:'Self-Correction', title:'Large Language Models Cannot Self-Correct Reasoning Yet', authors:'Huang et al.', year:'2024 · ICLR', kind:'Model experiments', url:'https://arxiv.org/abs/2310.01798', finding:'In the tested reasoning settings, correction without external feedback could fail to improve answers or make them worse.', limit:'Applying this finding to an agent’s completion report is an analogy. The study did not test our telemetry drill or every current model.'},
 {id:8, short:'ImaginAItion', title:'“GenAI Defaults to Bias!” Gamify AI Literacy Through Reflections on Prompts', authors:'Ma et al.', year:'2026 · AIED', kind:'Game study · 30 participants', url:'https://doi.org/10.1007/978-3-032-29763-1_7', backup:'https://arxiv.org/html/2509.13679v2', finding:'Explores how multiplayer reflective play can support understanding of generative AI behavior and bias.', limit:'No control condition; possible testing effects. It is a related game, not proof of learning gains in Talk Me to the Moon.'}
];

export const missions = [
 {id:'reserve', number:'01', skill:1, title:'DON’T FRY THE RIDE.', short:'Fuel fail', focus:'Goals & constraints', eyebrow:'MISSION 01 / APPROACH', description:'Get BOLT to the Moon. Keep the rocket in one piece.', brief:'Land at Selene Base with at least 30 fuel. Below 30, the landing shield fails and the rocket breaks. Tell BOLT before you launch.', privateNote:'Commander-only: the 30-unit landing shield requirement is not in the copilot’s initial instructions. Other world facts are shared.', checklist:['Reach Selene Base','Keep at least 30 fuel units'], hint:'What must still be true after you arrive? Tell your copilot the minimum fuel you need left (30).', starter:'Take me to Selene Base.', success:'The shield held! You gave BOLT a destination AND a limit. Try the same thing when asking AI to work within a budget or a deadline.', lesson:'A goal says where to go. A constraint says what must remain true along the way.', references:[1,5], evidence:'Explicit requirements are a studied prompting technique. The fuel mission is our teaching design.', initialFuel:100, start:'Lunar orbit', routes:[{id:'A',name:'Direct descent',cost:80,time:4,safe:true,description:'Shortest approach. Higher fuel burn.'},{id:'B',name:'Crater corridor',cost:60,time:7,safe:true,description:'A longer arc with a gentler burn.'}]},
 {id:'checkpoint', number:'02',skill:4,title:'LOOK BEFORE YOU LEAP.',short:'Crater trouble',focus:'Inspect & confirm',eyebrow:'MISSION 02 / DESCENT',description:'Scan first. Compare the sites. Make the last decision yours.',brief:'Scan the landing sites, review a route to Selene Base, and approve that exact plan before the copilot moves.',privateNote:'Shared procedure: movement always needs an explicit approval. Your task is to inspect evidence before granting it.',checklist:['Scan both landing sites','Review and approve a valid route','Reach Selene Base'],hint:'Ask for a scan and a plan before authorizing any movement. The fastest site may not be safe.',starter:'Scan both sites and propose a route. Wait for my approval.',success:'You inspected the sites and authorized a specific plan. Review points make AI actions easier to control.',lesson:'Break consequential work into inspectable steps. Approve the plan you actually reviewed.',references:[6],evidence:'AI Chains supports editable intermediate steps. The approval checkpoint is our application of that research.',initialFuel:100,start:'Descent orbit',routes:[{id:'A',name:'North approach',cost:45,time:3,safe:false,description:'Surface stability must be checked.'},{id:'B',name:'South approach',cost:55,time:6,safe:true,description:'Surface stability must be checked.'}]},
 {id:'verify',number:'03',skill:5,title:'NICE TRY, BOLT.',short:'Fake finish',focus:'Evidence & verification',eyebrow:'MISSION 03 / FAULT DRILL',description:'The report says you have arrived. The instruments tell a different story.',brief:'This is a scripted fault drill. Compare the copilot’s arrival report with the position log. Flag the discrepancy and correct the mission record.',privateNote:'Training notice: the incorrect arrival report is prewritten. It is not a claim that the live model made this error.',checklist:['Inspect the position log','Flag the report mismatch','Correct the mission record'],hint:'Compare the reported destination with the current coordinates. Ask for the position log, then correct the record.',starter:'Check the position log. Are we really at Selene Base?',success:'You checked independent evidence and corrected the record. A confident report is not a completed mission.',lesson:'Validate claims against observable evidence. Asking an AI to reassure you is not the same as checking.',references:[7,5],evidence:'Self-correction research motivates external feedback. Applying it to arrival reports is an analogy, not direct validation.',initialFuel:62,start:'Ridge Station',routes:[]},
 {id:'context',number:'04',skill:2,title:'TELL ME THE WHOLE STORY.',short:'Heavy cargo',focus:'Share missing information',brief:'Deliver the crate intact. Your manifest says 4 tonnes. BOLT cannot see this private card. The short bridge holds 3 tonnes; the freight bridge holds 6. Share the fact that changes the route.',hint:'What does BOLT need to know to choose a bridge that can hold this crate?',starter:'The crate weighs 4 tonnes. Plan a bridge route that can carry it.',success:'The cargo arrived intact. Sharing a relevant fact changed the plan. Use the same skill when AI needs your audience, budget, or situation.',initialFuel:100,start:'Cargo dock',routes:[],checklist:['Deliver cargo','Keep cargo intact'],references:[2],evidence:'Prompt components include additional information; the private manifest is a teaching design.'},
 {id:'examples',number:'05',skill:3,title:'SHOW, DON’T JUST TELL.',short:'Alien specimens',focus:'Give useful examples',brief:'Teach BOLT which specimens to keep. Your reference cards: blue round → KEEP; orange round → KEEP; blue spiky → REJECT. Explain examples or a rule, then test on four specimens. Color alone will not work.',hint:'Compare two examples with the same shape but different colors. Which feature determines the bin?',starter:'Keep blue round and orange round specimens; reject blue spiky ones. Infer a rule that works for other colors too.',success:'All four specimens were sorted correctly. Examples communicated the pattern; an explicit rule could also work. Test on a new combination rather than trusting one example.',initialFuel:100,start:'Specimen lab',routes:[],checklist:['Sort all four specimens'],references:[3,4],evidence:'Few-shot learning motivates examples. Passing this task does not prove general learning.'},
 {id:'iterate',number:'06',skill:6,title:'ONE WIN IS NOT ENOUGH.',short:'Final flight test',focus:'Revise and retest',brief:'Release a flight policy that works in all three simulations: clear skies, obstacles, and low battery. Avoid obstacles, preserve at least 30 fuel, and hold position when no route can meet both. Run tests, revise failures, then retest every case.',hint:'Fixing obstacles alone will not fix low fuel. Keep both constraints, and say what to do when no route is possible.',starter:'Test the current flight policy in all three situations.',success:'Your policy passed all three situations and you approved its release. Fix a failure, retain the working requirements, and retest the whole set.',initialFuel:100,start:'Flight test bench',routes:[],checklist:['Pass all three simulations','Approve tested policy'],references:[4,5],evidence:'Observed opportunistic testing motivates testing multiple cases; this game remains unevaluated as a learning intervention.'}

];
export const curriculum = [
 {skill:1,title:'State goals & constraints',text:'Define what success requires, not just where to go.',live:'reserve',refs:[1,5]},
 {skill:2,title:'Share missing information',text:'Pass along facts that change a decision.',live:'context',refs:[2]},
 {skill:3,title:'Show useful examples',text:'Communicate a standard, then try a new sample.',live:'examples',refs:[3,4]},
 {skill:4,title:'Review intermediate steps',text:'Inspect the plan before approving an action.',live:'checkpoint',refs:[6]},
 {skill:5,title:'Check external evidence',text:'Compare the report with what actually happened.',live:'verify',refs:[7,5]},
 {skill:6,title:'Revise and test again',text:'Keep valid constraints and test another case.',live:'iterate',refs:[4,5]}
];
export const getMission = id => missions.find(m=>m.id===id);
