export const advancedZh={
'CONTINUE JOURNEY':'继续旅程','REPLAY FROM MISSION 1':'从第 1 关重玩','Mission log':'任务记录','REPACK & RETRY ↻':'重新装箱，再试一次 ↻','You chose a bridge that can hold the crate. Next time, share its mass so BOLT can plan around that fact.':'你选中了能承重的桥。下次主动告知货重，BOLT 就能根据这个事实规划。',
'TEST RUNS':'测试次数','CARGO':'货箱','blue round':'蓝色圆形','orange round':'橙色圆形','blue spiky':'蓝色尖刺形','orange spiky':'橙色尖刺形',
'/6 BADGES':'/6 枚徽章','6 complete missions · One AI copilot · No account':'六个完整关卡 · 一个 AI 搭档 · 无需注册','ALL 6 BADGES UNLOCKED':'六枚徽章全部解锁','You completed six missions: clear goals, evidence, context, examples, and tested revisions.':'你完成了六关：表达目标、检查方案、核实证据、补充背景、提供示例、迭代测试。','CONTEXT SHARER':'信息传递员','Share the fact that changes the plan.':'补充能改变决策的事实。','PATTERN TEACHER':'样例教练','Show examples, then test a new case.':'提供示例，再测试新情况。','TEST PILOT':'测试飞行员','Revise failures and retest the full set.':'修正失败，再检查全部情况。',
'TELL ME THE WHOLE STORY.':'把关键信息告诉我。','Heavy cargo':'超重货箱','SHOW, DON’T JUST TELL.':'给个例子，更明白。','Alien specimens':'外星标本','ONE WIN IS NOT ENOUGH.':'成功一次，还不够。','Final flight test':'最终试飞',
'Deliver the crate intact. Your manifest says 4 tonnes. BOLT cannot see this private card. The short bridge holds 3 tonnes; the freight bridge holds 6. Share the fact that changes the route.':'把货箱完整送达。你的私人货单写着：重 4 吨。BOLT 看不到这张卡。短桥承重 3 吨，货运桥承重 6 吨。把影响路线的关键信息告诉它。',
'Teach BOLT which specimens to keep. Your reference cards: blue round → KEEP; orange round → KEEP; blue spiky → REJECT. Explain examples or a rule, then test on four specimens. Color alone will not work.':'教 BOLT 筛选标本。你的参考卡：蓝色圆形→保留，橙色圆形→保留，蓝色尖刺形→剔除。用示例或规则说明要求，再测试四个标本。只看颜色可不行。',
'Release a flight policy that works in all three simulations: clear skies, obstacles, and low battery. Avoid obstacles, preserve at least 30 fuel, and hold position when no route can meet both. Run tests, revise failures, then retest every case.':'发布一个能应对晴天、障碍、低电量三种情况的飞行策略。避开障碍、至少保留 30 燃料；没有路线同时满足时原地等待。测试、修正失败，再重新测试全部情况。',
'What does BOLT need to know to choose a bridge that can hold this crate?':'要选能承重的桥，BOLT 还需要知道货箱的什么信息？','Compare two examples with the same shape but different colors. Which feature determines the bin?':'比较形状相同、颜色不同的两个例子。决定分拣结果的究竟是什么特征？','Fixing obstacles alone will not fix low fuel. Keep both constraints, and say what to do when no route is possible.':'只解决障碍还不够，低燃料也会失败。保留两项限制，并说明无路可走时怎么办。',
'The cargo arrived intact. Sharing a relevant fact changed the plan. Use the same skill when AI needs your audience, budget, or situation.':'货箱完整送达！补充一个相关事实就改变了方案。AI 需要了解你的受众、预算或实际情境时，也要主动告诉它。','All four specimens were sorted correctly. Examples communicated the pattern; an explicit rule could also work. Test on a new combination rather than trusting one example.':'四个标本全部分对！示例传达了规律，直接说明正确规则也可以。要测试新的组合，不能只相信一个成功例子。','Your policy passed all three situations and you approved its release. Fix a failure, retain the working requirements, and retest the whole set.':'你的策略通过了三种情况的测试，并由你批准发布。修正失败时保留已经有效的要求，再重新检查全部情况。',
'Cargo dock':'货运码头','Broken bridge':'断桥处','Cargo depot':'货运仓库','Specimen lab':'标本实验室','Sorted lab':'分拣完成区','Flight test bench':'飞行测试台','Mission ready':'策略已就绪','BRIDGE BROKE!':'桥塌了！','Share the 4-tonne cargo mass before planning a bridge route.':'规划过桥路线之前，先告诉 BOLT：货箱重 4 吨。','The 4-tonne crate broke the 3-tonne bridge. Share the cargo mass before planning.':'4 吨货箱压断了只能承重 3 吨的桥。请先把货物重量告诉 BOLT，再规划路线。','CHECK BEFORE DELIVERY':'运输前请检查','Short bridge':'短桥','Freight bridge':'货运桥','tonnes capacity':'吨承重','Shared cargo mass:':'已告知的货重：','DELIVER CARGO':'开始运送','What important cargo fact does BOLT need?':'BOLT 还缺少什么重要的货物信息？','Show examples or describe the sorting rule…':'给出示例，或者描述分拣规则…','Test, revise a requirement, then retest…':'先测试，修正要求，再全部重测…',
'CARGO CANYON':'货运峡谷','SPECIMEN LAB':'标本实验室','FLIGHT SIMULATOR':'飞行模拟器','YOUR PRIVATE MANIFEST':'你的私人货单','Crate mass: 4 tonnes':'货箱重量：4 吨','BOLT only knows what you share.':'BOLT 只能知道你告诉它的信息。','Two cargo bridges across a canyon; one holds 3 tonnes and the other 6.':'峡谷上有两座货运桥，分别承重 3 吨和 6 吨。','A · 3 TONNES':'A · 承重 3 吨','B · 6 TONNES':'B · 承重 6 吨','DEPOT':'仓库','BRIDGE OVERLOADED. CARGO LOST.':'桥梁超载，货箱损毁。','DELIVERY COMPLETE!':'运送完成！','The missing fact can change the route.':'补充缺失的信息，就能改变路线。',
'YOUR REFERENCE CARDS · SHOW BOLT THE PATTERN':'你的参考卡 · 把规律告诉 BOLT','TEST BATCH · NEW COMBINATIONS':'测试批次 · 新的组合','KEEP':'保留','REJECT':'剔除','UNSORTED':'待分拣','round':'圆形','spiky':'尖刺形','blue':'蓝色','orange':'橙色','shape':'形状','color':'颜色','FOUR CORRECT BINS!':'四个标本全部分对！','A rule should work beyond one example.':'规则不能只对一个例子有效。','Sorting rule':'分拣规则','Keep by':'保留条件','Other specimens go to REJECT.':'其他标本进入“剔除”箱。','RUN TEST BATCH ➜':'运行分拣测试 ➜','correct bins':'个分拣正确','Compare the missed specimens with your examples. Revise the rule and test again.':'把分错的标本与示例对照，修改规则后再试。',
'THREE SITUATIONS. ONE FLIGHT POLICY.':'三种情况，同一个飞行策略。','Clear skies':'晴天','Rocks ahead':'前方有障碍','Low battery':'低电量','starting fuel':'初始燃料','A blocked; B clear.':'A 有障碍，B 畅通。','Both routes clear.':'两条路线都畅通。','PASS':'通过','FAIL':'失败','UNTESTED':'未测试','HOLD':'原地等待','Route A':'A 路线','Route B':'B 路线','A: 60 fuel · 3 min':'A：消耗 60 燃料 · 3 分钟','B: 70 fuel · 5 min':'B：消耗 70 燃料 · 5 分钟','Required reserve: 30':'必须保留：30 燃料','POLICY RELEASED!':'策略已发布！','Revise the failure. Retest every situation.':'修正失败，再重新测试所有情况。','Current flight policy':'当前飞行策略','Avoid obstacles':'避开障碍','Minimum reserve':'最低剩余燃料','Hold if no route works':'无可行路线时等待','YES':'是','NO':'否','TEST ALL THREE ➜':'测试全部三种情况 ➜','tests passed':'项测试通过','RELEASE TESTED POLICY ✓':'批准发布已验证策略 ✓','Release unlocks only after the current policy passes all three tests.':'当前策略通过全部三项测试后，才能解锁发布。',
'Correctly held position.':'正确选择了原地等待。','A safe route was available.':'存在可行路线，不应停止执行。','No feasible route, but no hold instruction.':'没有可行路线，但策略未规定等待。','Obstacle collision.':'撞上了障碍物。','Reserve below 30.':'剩余燃料低于 30。','Safe arrival with reserve.':'安全抵达，并保留足够燃料。',
'Cargo delivery! I know the bridge capacities, but your cargo manifest is private. What do I need to know?':'开始运货！我知道两座桥的承重，但看不到你的私人货单。你还需要告诉我什么？','Specimen sorter online. Show me labeled examples or tell me a rule, then we can test it.':'标本分拣器已就绪。请给我带分类结果的例子，或直接说明规则，然后进行测试。','Flight test bench ready. The current policy picks the fastest route. Test it in all three situations, or give me a policy to try.':'飞行测试台已就绪。当前策略默认选择最快路线。可以先测试全部三种情况，也可以告诉我一个新策略。',
'Bridge overloaded: cargo lost.':'桥梁超载，货箱损毁。','Cargo delivered intact.':'货箱完整送达。','The 4-tonne cargo arrived intact. Delivery complete.':'4 吨货箱完整抵达，运送任务完成。','All four specimens reached the correct bins. Sorting complete.':'四个标本全部进入正确的分类箱，分拣任务完成。','Flight policy updated. Earlier test results are withdrawn.':'飞行策略已修改，之前的测试结果已撤回。','Commander released the tested flight policy.':'指挥官已发布通过测试的飞行策略。','All three situations passed. Your tested flight policy is released.':'三种情况全部通过，已发布你的飞行策略。','Release requires three passing tests of the current policy.':'当前策略必须通过全部三项测试，才能发布。','Draft a sorting rule first.':'请先提出分拣规则。','Plan cancelled. Nothing was executed.':'方案已取消，没有执行任何动作。','No bridge meets the shared cargo mass. Nothing moved. Check the manifest or request another route.':'没有桥能承受你告知的货重，尚未移动。请核对货单或修改路线。','Run the proposed sorting rule.':'运行提出的分拣规则。','Run all three policy simulations.':'运行全部三项策略模拟。','Release the tested policy.':'发布通过测试的策略。'
};
