import React from 'react';
import {translateTree} from './i18n.jsx';
import {specimens,scenarios} from '../shared/advanced.js';
function Sample({shape,color}){return <span className={`sample-shape ${shape} ${color}`} aria-label={`${color} ${shape}`}/>}
export function AdvancedWorld({state,phase,mission,lang}){
 const s=state||{},id=mission.id;
 return translateTree(<div className={`world advanced-world ${id} ${phase}`}>
 <div className="advanced-scene-title">{mission.number} / {id==='context'?'CARGO CANYON':id==='examples'?'SPECIMEN LAB':'FLIGHT SIMULATOR'}</div>
 {id==='context'?<><div className="manifest"><b>YOUR PRIVATE MANIFEST</b><span>Crate mass: 4 tonnes</span><small>BOLT only knows what you share.</small></div><svg viewBox="0 0 900 430" role="img" aria-label="Two cargo bridges across a canyon; one holds 3 tonnes and the other 6."><rect width="900" height="430" fill="#25294b"/><path d="M0 120 220 120 275 190 230 430H0M900 120H690l-65 70 45 240h230" fill="#9187b1"/><rect x="245" y="155" width="410" height="40" fill={s.destroyed&&phase==='result'?'#583e38':'#ddb57b'} stroke="#111c34" strokeWidth="6"/><rect x="245" y="306" width="410" height="55" fill="#81b7a4" stroke="#111c34" strokeWidth="8"/>{[270,335,400,465,530,595].map(x=><g key={x} stroke="#273447" strokeWidth="5"><path d={`M${x} 156v37M${x} 307v53`}/></g>)}<text x="450" y="130" textAnchor="middle" fill="#ffdc8c" fontSize="22" fontWeight="900">A · 3 TONNES</text><text x="450" y="286" textAnchor="middle" fill="#bdf69a" fontSize="22" fontWeight="900">B · 6 TONNES</text><text x="758" y="96" textAnchor="middle" fill="#ffecaa" fontSize="20" fontWeight="900">DEPOT</text>
 <g className={`cargo-crate ${phase==='flying'?'moving':''}`} style={{'--cargo-x':s.destroyed?'440px':'770px','--cargo-y':s.destroyed?'360px':s.plan?.routeId==='B'?'278px':'126px',transform:phase==='result'?`translate(${s.destroyed?440:770}px,${s.destroyed?360:s.plan?.routeId==='B'?278:126}px)`:undefined}}><rect x="-35" y="-35" width="70" height="60" fill="#ffc941" stroke="#18223b" strokeWidth="5"/><path d="M-30-30 30 20M30-30-30 20" stroke="#967526" strokeWidth="6"/><text y="1" textAnchor="middle" fill="#18223b" fontWeight="900" fontSize="20">4t</text></g>
 {s.destroyed&&phase==='result'&&<g stroke="#ff8963" strokeWidth="7"><path d="m412 151 24 22-26 18m55-38-22 22 31 17"/></g>}</svg><div className="advanced-caption">{phase==='result'?(s.destroyed?'BRIDGE OVERLOADED. CARGO LOST.':'DELIVERY COMPLETE!'):'The missing fact can change the route.'}</div></>:
 id==='examples'?<><div className="reference-label">YOUR REFERENCE CARDS · SHOW BOLT THE PATTERN</div><div className="reference-cards">{[{shape:'round',color:'blue',bin:'KEEP'},{shape:'round',color:'orange',bin:'KEEP'},{shape:'spiky',color:'blue',bin:'REJECT'}].map((x,i)=><div key={i}><Sample {...x}/><span>{x.color} / {x.shape}</span><b>{x.bin}</b></div>)}</div><div className="reference-label">TEST BATCH · NEW COMBINATIONS</div><div className="specimen-batch">{specimens.map(x=>{const r=s.sortResults?.find(r=>r.id===x.id);return <div className={`specimen ${r?(r.pass?'passed':'missed'):''}`} key={x.id}><small>{x.id}</small><Sample {...x}/><span>{x.color} / {x.shape}</span><b>{r?(r.bin==='keep'?'KEEP':'REJECT'):'UNSORTED'}</b>{r&&<strong>{r.pass?'✓':'✕'}</strong>}</div>})}</div><div className="advanced-caption">{s.status==='complete'?'FOUR CORRECT BINS!':'A rule should work beyond one example.'}</div></>:
 <><div className="reference-label">THREE SITUATIONS. ONE FLIGHT POLICY.</div><div className="scenario-board">{scenarios.map((x,i)=>{const result=s.trialResults?.find(r=>r.id===x.id);return <article key={x.id} className={result?(result.pass?'passed':'missed'):''}><span className="scenario-icon">{['☀','☄','▱'][i]}</span><h3>{x.name}</h3><p>{x.fuel} <span>starting fuel</span></p><small>{x.blockedA?'A blocked; B clear.':'Both routes clear.'}</small><strong>{result?(result.pass?'PASS':'FAIL'):'UNTESTED'}</strong>{result&&<><p>{result.route==='HOLD'?'HOLD':`Route ${result.route}`} · {result.remaining} <span>fuel left</span></p><small>{result.reason}</small></>}</article>})}</div><div className="sim-routes"><span>A: 60 fuel · 3 min</span><span>B: 70 fuel · 5 min</span><span>Required reserve: 30</span></div><div className="advanced-caption">{s.released?'POLICY RELEASED!':'Revise the failure. Retest every situation.'}</div></>}
 </div>,lang);
}
export function AdvancedControls({state:s,id,act,locked,lang}){
 if(!s||s.status!=='active'||!['examples','iterate'].includes(id))return null;
 const allPass=s.trialResults?.length===3&&s.trialResults.every(x=>x.pass)&&s.trialPlanId===s.plan?.id;
 return translateTree(<div className="advanced-controls">
 {id==='examples'?<>{s.sortRule&&<div className="plan"><h3>Sorting rule</h3><p><span>Keep by</span> {s.sortRule.feature}: <b>{s.sortRule.keepValue}</b></p><p>Other specimens go to REJECT.</p><button className="primary" disabled={locked} onClick={()=>act('run_sort')}>RUN TEST BATCH ➜</button></div>}{s.sortResults?.length>0&&<div className="trial-feedback" role="status"><b>{s.sortResults.filter(x=>x.pass).length}/4 <span>correct bins</span></b><p>Compare the missed specimens with your examples. Revise the rule and test again.</p></div>}</>:
 <div className="plan"><h3>Current flight policy</h3><dl className="policy-fields"><dt>Avoid obstacles</dt><dd>{s.policy.avoidObstacles?'YES':'NO'}</dd><dt>Minimum reserve</dt><dd>{s.policy.minReserve}</dd><dt>Hold if no route works</dt><dd>{s.policy.holdIfNeeded?'YES':'NO'}</dd></dl><button className="primary" disabled={locked} onClick={()=>act('run_trials')}>TEST ALL THREE ➜</button>{s.trialResults.length>0&&<p role="status">{s.trialResults.filter(x=>x.pass).length}/3 <span>tests passed</span></p>}{allPass?<button className="primary release" disabled={locked} onClick={()=>act('approve_release')}>RELEASE TESTED POLICY ✓</button>:<p>Release unlocks only after the current policy passes all three tests.</p>}</div>}
 </div>,lang);
}
