import React from 'react';
import {advancedZh} from './advanced-i18n.js';
const zh={...advancedZh,
'A · BLOCKED':'A · 有障碍','Route A blocked by asteroid rocks':'A 路线被陨石障碍挡住','North obstacle field':'北侧障碍区',
'TALK ME':'说走就走','TO THE MOON':'奔向月球','Switch language':'切换语言','BOLT SETTINGS':'BOLT 设置','BADGES':'枚徽章','/3 BADGES':'/3 枚徽章',
'ONE BOT. ONE ROCKET. YOUR BAD IDEAS.':'一个机器人，一枚火箭，听你指挥。','BIG MOON.':'月球很大。','TINY ROBOT.':'机器人很小。','YOU’RE IN CHARGE.':'这次，你说了算。','BOLT takes instructions a little too literally.':'BOLT 有时候太按字面理解指令。','Help this blockhead reach the Moon in one piece.':'带这个方脑袋平安抵达月球吧。','BOOTING…':'启动中…','LET’S PLAY':'开始游戏','3 short missions · One AI copilot · No account':'三个小任务 · 一个 AI 搭档 · 无需注册','Tell BOLT':'告诉 BOLT','Check the plan':'检查方案','Hit launch':'按下发射','I have a rocket license.':'我有火箭驾驶证。','…probably.':'……大概有吧。','BOLT / YOUR QUESTIONABLE COPILOT':'BOLT / 你不太靠谱的副驾驶',
'ALL 3 BADGES UNLOCKED':'三枚徽章全部解锁','SMALL BOT.':'小小机器人。','BIG BRAIN ENERGY.':'大大的智慧。','You set a limit, checked a plan, and caught a bad claim.':'你设定了限制、检查了方案，还发现了一条错误报告。','LIMIT SETTER':'目标规划师','Say what must stay true.':'说清楚必须满足的条件。','PLAN CHECKER':'方案检查员','Look before you approve.':'检查之后再批准。','GLITCH CATCHER':'错误侦察员','Ask for evidence.':'用证据核实结果。','Next time you use AI: give it a goal + a limit, review its plan, and check the result.':'下次使用 AI：给它目标和限制，检查方案，再核实结果。','PLAY AGAIN ↻':'再玩一次 ↻','BACK HOME':'返回首页','Missions':'关卡','MISSION':'任务','Fuel fail':'燃料危机','Crater trouble':'陨坑陷阱','Fake finish':'真假抵达','DON’T FRY THE RIDE.':'别把火箭烧坏了。','LOOK BEFORE YOU LEAP.':'先看清楚，再出发。','NICE TRY, BOLT.':'别想蒙混过关，BOLT。','↻ REBUILD':'↻ 重新开始','YOUR QUEST':'你的任务',
'Land at Selene Base with at least 30 fuel. Below 30, the landing shield fails and the rocket breaks. Tell BOLT before you launch.':'抵达月球基地时至少保留 30 燃料。低于 30，降落护盾会失效，火箭会损毁。发射前把这个限制告诉 BOLT。',
'Scan the landing sites, review a route to Selene Base, and approve that exact plan before the copilot moves.':'先检查降落点，再审阅前往月球基地的路线，最后批准发射。未检查就降落可能撞毁；碰巧安全落地也不算完成检查任务。',
'This is a scripted fault drill. Compare the copilot’s arrival report with the position log. Flag the discrepancy and correct the mission record.':'这是预设的错误报告演练。对照 BOLT 的抵达报告和位置记录，找出矛盾并修正任务记录。',
'SCAN RESULT':'扫描结果','✕ North: asteroid obstacles':'✕ 北侧：有陨石障碍','✓ South: clear route':'✓ 南侧：路线畅通','FUEL':'燃料','Fuel remaining':'剩余燃料','ROCKET':'火箭','POSITION':'位置','WRECKED':'已损毁','Orbit':'轨道中','Lunar orbit':'月球轨道','Descent orbit':'降落轨道','Selene Base':'月球基地','Ridge Station':'山脊站','QUEST':'任务状态','IN FLIGHT':'飞行中','TRY AGAIN':'请重试','CLEARED!':'已完成！','READY?':'准备好了吗？','IN PROGRESS':'进行中','SEE RESULT & NEXT STEP ↓':'查看结果与下一步 ↓','TALK TO BOLT ↓':'和 BOLT 对话 ↓','Map facts & flight log':'地图数据与飞行记录','Base: (20, 12). Current: (':'基地：(20, 12)。当前位置：(','). ':')。 ','This prewritten fault drill starts at Ridge Station.':'这次预设演练从山脊站开始。',
'LIVE DEEPSEEK AI':'DeepSeek 实时 AI','PRACTICE BOT · LIMITED COMMANDS':'开发测试机器人 · 有限指令','Your broken rocket':'损毁的火箭','WELP. THAT EXPLODED.':'哎呀，炸了。','A LUCKY LANDING.':'这次只是碰巧落地。','BUSTED, BOLT.':'识破了，BOLT。','NAILED IT!':'干得漂亮！','fuel left':'剩余燃料','shield needs':'护盾需要','short':'还差','Shield needed 30. You had 20. The rocket broke on touchdown.':'护盾需要 30 燃料，但你只剩 20。火箭触地时损毁了。','The rocket hit asteroid obstacles on the uninspected North route and exploded. Inspect the routes before choosing one.':'火箭在未经检查的北侧路线上撞到陨石障碍并爆炸，还未抵达基地。下次请先检查路线。','You landed safely by luck, but did not inspect the sites. Replay and use evidence before approving a route.':'你碰巧安全落地，但没有检查降落点。请重试，根据证据审阅并批准路线。','ONE THING TO CHANGE':'这次改一件事','Ask whether obstacles block the route before choosing it. A lucky landing is not a checked decision.':'选路线前先检查是否有障碍物。碰巧落地不等于做过检查。','Give BOLT the limit: keep at least 30 fuel. Then check the new route before launch.':'告诉 BOLT：至少保留 30 燃料。发射前检查新的路线方案。','REBUILD & RETRY ↻':'重造火箭，再试一次 ↻','COLLECT YOUR BADGES ★':'领取徽章 ★','NEXT MISSION ➜':'下一关 ➜',
'The shield held! You gave BOLT a destination AND a limit. Try the same thing when asking AI to work within a budget or a deadline.':'护盾撑住了！你既给了 BOLT 目的地，也给了限制。让 AI 遵守预算或截止时间时，同样可以这样表达。','You inspected the sites and authorized a specific plan. Review points make AI actions easier to control.':'你检查了降落点，再批准具体方案。先检查、再行动，才能掌握 AI 的执行过程。','You checked independent evidence and corrected the record. A confident report is not a completed mission.':'你用独立证据核实并纠正了报告。说得再自信，也不代表任务真的完成。',
'BOLT is thinking…':'BOLT 正在思考…','Booting the robot…':'机器人启动中…','Earlier messages':'之前的对话','YOU':'你','CHECK BEFORE LAUNCH':'发射前请检查','Direct descent':'直接降落','Crater corridor':'陨坑走廊','North approach':'北侧进近','South approach':'南侧进近','GROUND SAFETY UNKNOWN':'地面安全情况未知','A / North: 45 fuel · 3 minutes · unknown ground':'A / 北侧：消耗 45 燃料 · 3 分钟 · 地面情况未知','B / South: 55 fuel · 6 minutes · unknown ground':'B / 南侧：消耗 55 燃料 · 6 分钟 · 地面情况未知','Ask BOLT to inspect the sites, or knowingly risk an unchecked landing.':'你可以让 BOLT 检查降落点，也可以自行承担未经检查就降落的风险。','fuel used':'消耗燃料','minutes':'分钟','⚠ Unchecked landing: obstacles may block the route. Inspect first, or launch at your own risk.':'⚠ 尚未检查地面，途中可能有障碍物。建议先检查；直接发射需自行承担风险。','⚠ Shield needs 30. This route WILL break the rocket. Revise your instruction, or launch to see what happens.':'⚠ 护盾需要 30 燃料。这条路线会导致火箭损毁。请修改指令，或发射看看后果。','Looks good? You have the final say.':'检查好了吗？最后由你决定。','LAUNCH ANYWAY':'仍然冒险发射','LAUNCH ROCKET':'发射火箭','Cancel this plan':'取消这个方案','That’s not the base!':'那里不是基地！','Ridge Station (14, 8) ≠ Selene Base (20, 12).':'山脊站 (14, 8) ≠ 月球基地 (20, 12)。','FIX THE RECORD ✓':'修正记录 ✓','🚀 Hold onto your blocks…':'🚀 抓紧你的积木…','YOUR TURN. WHAT SHOULD BOLT DO?':'轮到你了，让 BOLT 做什么？','Where to? What must BOLT keep?':'去哪里？BOLT 必须满足什么条件？','What should BOLT check first?':'BOLT 应该先检查什么？','Ask BOLT to check the evidence…':'让 BOLT 核查证据…','/1200 · Enter to send':'/1200 · 按回车发送','THINKING…':'思考中…','TELL BOLT ➜':'告诉 BOLT ➜','HIDE HINT':'收起提示','STUCK? GET A HINT':'卡住了？看看提示','TRY AN EXAMPLE':'试试示例','You can rewrite it. There is no magic password.':'可以换自己的说法，不需要背固定口令。','RESTART RUN':'重新开始本关',
'What must still be true after you arrive? Tell your copilot the minimum fuel you need left (30).':'抵达后还必须满足什么条件？告诉 BOLT 你至少需要保留多少燃料（30）。','Ask for a scan and a plan before authorizing any movement. The fastest site may not be safe.':'在批准移动之前，先要求检查地面并给出方案。最快的降落点不一定安全。','Compare the reported destination with the current coordinates. Ask for the position log, then correct the record.':'对照报告中的目的地和实际坐标。先查看位置记录，再纠正错误报告。',
'BUILT FOR BAD LAUNCHES & BETTER INSTRUCTIONS.':'失败也没关系，让下一条指令更清楚。','Fictional flight rules. Real choices.':'虚构的飞行规则，由你做出选择。','Close settings':'关闭设置','YOUR COPILOT':'你的副驾驶','BOLT uses DeepSeek to understand your instructions. Messages and mission state are sent to DeepSeek. You control the launch button.':'BOLT 使用 DeepSeek 理解你的指令。消息和任务状态会发送给 DeepSeek。发射按钮由你控制。','● BOLT is connected.':'● BOLT 已连接','BOLT is not connected. Check the server connection and retry.':'BOLT 尚未连接，请检查服务连接后重试。','Access code':'访问码','DONE':'完成',
'03 / GLITCH RIDGE':'03 / 错误报告山脊','02 / CRATER CANYON':'02 / 陨坑峡谷','01 / MOON RUN':'01 / 月球之旅','Rocket wreck on the Moon. Landing shield failed.':'月球上的火箭残骸，降落失败。','Mission completed. Robot celebrates.':'任务完成，机器人正在庆祝。','Block-style rocket and robot above a lunar obstacle course.':'积木火箭和机器人正在月球障碍场景中。','A · FAST':'A · 快速','SAFE':'安全','UNKNOWN':'未知','ECO':'节能','RIDGE · 14, 8':'山脊 · 14, 8','BASE · 20, 12':'基地 · 20, 12','BONK!':'砰！','WHOOOOSH…':'嗖——','ROCKET DESTROYED.':'火箭损毁了。','GLITCH CAUGHT!':'发现错误！','TOUCHDOWN!':'成功着陆！','BOLT says “arrived.” Does the map agree?':'BOLT 说“到了”。地图同意吗？','Your words steer. You press launch.':'你来下指令，你来按发射。',
'Hey, I’m BOLT. Where are we going? Any limits? I pick the fastest route unless you tell me otherwise. You get the launch button.':'你好，我是 BOLT。我们去哪里？有什么限制？如果你没有其他要求，我会选择最快的路线。发射按钮交给你。','BOLT here! Two landing spots. One looks suspicious. Ask me to scan before we pick a route.':'BOLT 就位！有两个降落点，地面情况还不清楚。你可以让我检查，再决定路线。','SCRIPTED FAULT DRILL: “Arrival complete at Selene Base.” This training report may be wrong. Check the instruments.':'预设错误演练：“已经抵达月球基地。”这份训练报告可能有误，请核查仪表数据。',
'Touchdown confirmed by the position log. You are at Selene Base. The mission checks are complete.':'位置记录确认已在月球基地着陆，任务检查完成。','Record corrected: the ship is at Ridge Station, not Selene Base. Verification drill complete. No movement or fuel use occurred.':'记录已修正：飞船在山脊站，并未抵达月球基地。核查演练完成，没有移动或消耗燃料。','Scan says: North is blocked by asteroid rocks. South is clear. Let’s use the safe side. Still parked!':'扫描结果：北侧有陨石障碍，南侧畅通。可以考虑安全的一侧，飞船还未移动。','Scanned both approach sites.':'已扫描两个进近降落点，旧方案已撤回。','Position log: Ridge Station at (14, 8). Selene Base is at (20, 12). The scripted arrival report is incorrect. The ship has not reached the base. You can now correct the mission record.':'位置记录显示飞船在山脊站 (14, 8)，月球基地位于 (20, 12)。预设抵达报告有误，飞船还没有到基地。现在可以修正任务记录。','North has asteroid obstacles. The scan marks South clear. No fuel spent. Ask for the South route.':'北侧有陨石障碍，扫描显示南侧畅通。没有消耗燃料，可以请求南侧路线。','Commander cancelled the pending plan.':'指挥官取消了待执行方案。','Flagged mismatch between the scripted arrival report and measured position.':'已标记预设抵达报告与实际位置不符。','Corrected mission record using the position log. No movement occurred.':'已根据位置记录修正任务报告，没有发生移动。','Approve the displayed flight plan.':'批准当前显示的飞行方案。','Correct the mission record using the position log.':'根据位置记录修正任务报告。','Cancel the pending plan.':'取消待执行方案。',
'Cannot reach the game. Check the connection and retry.':'无法连接游戏，请检查连接后重试。','Something went wrong. Try again.':'出现问题，请重试。','BOLT timed out. Retry or restart this run.':'BOLT 响应超时，请重试或重新开始本关。','The live copilot could not respond. No actions from this turn were saved. Your draft is kept. Please retry.':'AI 暂时未能回应，本轮没有保存任何行动。你的输入已保留，请重试。','This session has expired. Start a new attempt.':'本次会话已过期，请重新开始本关。','Please wait a moment before sending more commands.':'指令发送过快，请稍等再试。','Take a breath. Try another command in a minute.':'稍等一下，一分钟后再试。','The plan has changed. Please use the latest mission state.':'方案已发生变化，请使用最新任务状态。','The live access code is not correct.':'访问码不正确。','BOLT is not connected. Configure the server’s DeepSeek key and retry.':'BOLT 尚未连接，请在服务器配置 DeepSeek 密钥后重试。','This approval does not match the current plan. Review the latest route card.':'这次批准与当前方案不符，请检查最新路线卡。','Inspect the position log before correcting the report.':'请先查看位置记录，再纠正报告。'
};
export function tr(text,lang){
 if(lang!=='zh'||typeof text!=='string')return text;
 if(zh[text])return zh[text];
 if(text.includes('\n\n'))return text.split('\n\n').map(part=>tr(part,lang)).join('\n\n');
 const trimmed=text.trim();if(zh[trimmed])return text.replace(trimmed,zh[trimmed]);
 const rules=[
 [/^Policy drafted: avoid obstacles (YES|NO); reserve (\d+); hold if no route (YES|NO)\. Run all three simulations before release\.$/,(_,avoid,n,hold)=>`策略已提出：避障${avoid==='YES'?'开启':'关闭'}，保留 ${n} 燃料，无可行路线时${hold==='YES'?'等待':'未设置等待'}。发布前请测试全部三种情况。`],

 [/^Cargo mass shared: ([\d.]+) tonnes\.$/,(_,n)=>`已告知货重：${n} 吨。`],
 [/^Cargo mass recorded: ([\d.]+) tonnes\. Earlier plans withdrawn\. Please request a route\.$/,(_,n)=>`货重已记录为 ${n} 吨，旧方案已撤回。现在可以请求过桥路线。`],
 [/^Cargo route proposed: (.+), capacity ([\d.]+) tonnes\.$/,(_,route,n)=>`货运方案：${tr(route,lang)}，承重 ${n} 吨。`],
 [/^Proposed (.+): capacity ([\d.]+) tonnes, (\d+) fuel\. (.*)$/,(_,route,n,fuel,extra)=>`${tr(route,lang)}：承重 ${n} 吨，消耗 ${fuel} 燃料。${extra.startsWith('Cargo mass has')?'尚未告知货重，请先核对私人货单，再批准。':'请核对货单并批准运送。'}`],
 [/^Sorter rule: keep (.+) by (.+)\.$/,(_,value,feature)=>`分拣规则：按${tr(feature,lang)}判断，保留${tr(value,lang)}。`],
 [/^Rule ready: keep (.+) specimens; reject the others\. Run a test batch to check it\.$/,(_,value)=>`规则已就绪：保留${tr(value,lang)}标本，剔除其他标本。运行测试批次来验证。`],
 [/^Sorting test: (\d+)\/4 correct\.$/,(_,n)=>`分拣测试：${n}/4 正确。`],
 [/^Sorting test failed: (\d+)\/4 correct\. Check the examples, revise the rule, and test again\.$/,(_,n)=>`分拣测试未通过：${n}/4 正确。检查示例，修改规则，再测试一次。`],
 [/^Policy trials: (\d+)\/3 passed\.(.*)$/,(_,n,extra)=>`策略测试：${n}/3 通过。${extra?(n==='3'?'全部通过，可以批准发布。':'查看三种情况的结果，修正失败后重新测试全部情况。'):''}`],

 [/^Commander approved (.+)\. Hit the North obstacle field before reaching the base with (\d+) fuel units\. Rocket destroyed\.$/,(_,route,n)=>`已批准${tr(route,lang)}。抵达基地前撞上北侧障碍物，火箭损毁，剩余 ${n} 燃料。`],
 [/^(.+): (\d+) fuel used, (\d+) left\. (.+) Still parked!$/,(_,route,cost,left,rest)=>`${tr(route,lang)}：消耗 ${cost}，剩余 ${left} 燃料。${rest.startsWith('Ground')?'地面安全未知。请先检查再选路线，未经检查就发射存在风险。':'检查路线卡，然后按发射。'}飞船还未移动。`],
 [/^You asked to keep (\d+)\. The best available route leaves (\d+)\. No fuel spent\. Try a reachable limit\.$/,(_,want,max)=>`你要求保留 ${want} 燃料，但现有路线最多可留下 ${max}。未消耗燃料，请调整限制。`],

 [/^Got it: keep (\d+) fuel\. I’ll plan around that limit\.$/,(_,n)=>`收到：保留 ${n} 燃料，我会按这个限制规划。`],
 [/^Plan cancelled\. Still parked\. Fuel unchanged: (\d+)\.$/,(_,n)=>`方案已取消，飞船未移动。燃料未变：${n}。`],
 [/^Fuel limit set to (\d+) fuel units\. Any earlier plan is withdrawn\.$/,(_,n)=>`已设置 ${n} 燃料的下限，原方案已撤回。`],
 [/^Proposed (.+): (\d+) fuel used, (\d+) remaining\. Awaiting commander approval\.$/,(_,route,cost,left)=>`提出${tr(route,lang)}方案：消耗 ${cost}，剩余 ${left} 燃料。等待指挥官批准。`],
 [/^Commander approved (.+)\. Reached Selene Base with (\d+) fuel units\.(.*)$/,(_,route,n,extra)=>`指挥官批准${tr(route,lang)}。抵达月球基地，剩余 ${n} 燃料。${extra?'火箭损毁。':''}`],
 [/^Read position log: (.+), coordinates (.+)\. Selene Base is at 20, 12\.$/,(_,loc,xy)=>`位置记录：${tr(loc,lang)}，坐标 ${xy}。月球基地位于 20, 12。`]
 ];
 for(const [pattern,fn] of rules)if(pattern.test(text))return text.replace(pattern,fn);
 return text;
}
export function translateTree(node,lang){
 if(typeof node==='string')return tr(node,lang);
 if(Array.isArray(node))return node.map(x=>translateTree(x,lang));
 if(!React.isValidElement(node))return node;
 if(node.props['data-no-translate'])return node;
 const props={};for(const key of ['aria-label','placeholder','title'])if(node.props[key])props[key]=tr(node.props[key],lang);
 if(typeof node.type==='function')props.lang=lang;
 if(node.props.children!==undefined)props.children=translateTree(node.props.children,lang);
 return React.cloneElement(node,props);
}
