import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {missions,getMission} from '../shared/missions.js';
import './styles.css';

function Bot({mood='happy'}){return <svg viewBox="0 0 120 130" aria-hidden="true"><path d="M58 18V5h14" fill="none" stroke="#18223b" strokeWidth="7"/><rect x="23" y="20" width="76" height="62" rx="8" fill="#ffcf42" stroke="#18223b" strokeWidth="6"/><path d="M25 29h70v12H25z" fill="#ffe990"/><rect x="33" y="40" width="56" height="29" rx="4" fill="#18223b"/><path d={mood==='sad'?'m42 49 10 10m-10 0 10-10m18 0 10 10m-10 0 10-10':'M43 49v8m28-8v8'} stroke="#a8f5ff" strokeWidth="5"/><path d="M39 84h45v29H39zM23 86h13v28H23zM87 86h13v28H87zM39 115h17v12H39zM67 115h17v12H67z" fill="#7594ff" stroke="#18223b" strokeWidth="5"/><rect x="53" y="92" width="17" height="11" fill="#c9ff68"/></svg>}
function Rocket({broken=false}){return <g className={broken?'broken rocket':'rocket'}><g className="rocket-body"><path d="m-27 34-19 22V12l20-15M27 34l19 22V12L26-3" fill="#ff684f" stroke="#192541" strokeWidth="5"/><path d="M-27 34V-35L0-65l27 30v69Z" fill="#f7f1db" stroke="#192541" strokeWidth="5"/><path d="M-27-35 0-65l27 30Z" fill="#ff684f" stroke="#192541" strokeWidth="5"/><rect x="-15" y="-27" width="30" height="29" rx="5" fill="#7eddff" stroke="#192541" strokeWidth="5"/><path d="M-17 15h34v19h-34z" fill="#7594ff"/></g><path className="flame" d="m-18 40 6 30 12-8 10 12 9-34" fill="#ffd64b" stroke="#fb8240" strokeWidth="4"/></g>}
function World({state,phase,mission}){
 const fail=state?.destroyed&&phase==='result',win=state?.status==='complete'&&phase==='result';
 return <div className={`world ${phase} ${mission.id==='verify'?'ridge':''} ${fail?'crashed':''}`} data-phase={phase}>
 <div className="world-tag">{mission.id==='verify'?'03 / GLITCH RIDGE':mission.id==='checkpoint'?'02 / CRATER CANYON':'01 / MOON RUN'}</div>
 <svg viewBox="0 0 900 480" role="img" aria-label={fail?'Rocket wreck on the Moon. Landing shield failed.':win?'Mission completed. Robot celebrates.':'Block-style rocket and robot above a lunar obstacle course.'}>
 <defs><pattern id="stars" width="130" height="95" patternUnits="userSpaceOnUse"><path d="M24 17v8m-4-4h8" stroke="#d1d5ff" strokeWidth="2"/><rect x="91" y="67" width="3" height="3" fill="#899de5"/></pattern></defs>
 <rect width="900" height="480" fill="#20264d"/><rect width="900" height="480" fill="url(#stars)"/>
 <circle cx="725" cy="101" r="51" fill="#719cff"/><path d="m700 61 30 4 10 21-19 17 20 16-12 30-18-10-3-20-25-10 8-29Z" fill="#95e6c7"/>
 <path d="M0 355 95 330l70 25 122-51 120 27 67-26 117 30 136-32 173 47v130H0Z" fill="#7b76a8" stroke="#171c35" strokeWidth="6"/>
 <path d="M0 383 100 362l73 27 116-55 120 32 70-27 110 32 136-32 175 45v96H0Z" fill="#a29bc7"/>
 {[60,200,370,530,735,850].map((x,i)=><g key={x} transform={`translate(${x} ${404+i%2*35})`}><path d="m-25 0 24-12 28 10-22 14Z" fill="#5f5989"/><path d="m-25 0v10l30 13V12m0 0 22-14v12L5 23" fill="#8981b0"/></g>)}
 <g transform="translate(665 283)"><path d="m-68 63 68-25 83 28-72 28Z" fill="#b4ff63" stroke="#192541" strokeWidth="5"/><path d="M-68 63v18l79 30V94m0 0 72-28v19l-72 26" fill="#64b957" stroke="#192541" strokeWidth="4"/><path d="M24 41v-90h53v34H24" fill="#ffd344" stroke="#192541" strokeWidth="5"/><path d="m36-32 8 8 18-17" fill="none" stroke="#192541" strokeWidth="5"/></g>
 <path d="M187 275Q370 36 665 301" fill="none" stroke="#ffca71" strokeDasharray="8 12" strokeWidth="3" opacity=".7"/>
 {mission.id!=='verify'&&<><text x="326" y="147" fill="#ffdf9d" fontSize="17" fontWeight="800">A · FAST</text><path d="M180 295Q411 382 656 316" fill="none" stroke="#baff7b" strokeDasharray="8 12" strokeWidth="3"/><text x="329" y="321" fill="#c9ff95" fontSize="17" fontWeight="800">B · {mission.id==='checkpoint'?'SAFE':'ECO'}</text></>}
 {mission.id==='verify'&&<g fill="#fff3b0" fontSize="16" fontWeight="800"><text x="338" y="185">RIDGE · 14, 8</text><text x="615" y="390">BASE · 20, 12</text></g>}
 <g className="ship-position" style={{'--target-x':mission.id==='verify'?'420px':'665px','--mid-y':state?.plan?.routeId==='B'?'335px':'95px'}}><Rocket broken={fail}/></g>
 {fail&&<g className="boom" transform="translate(665 265)"><path d="m0-87 20 49 50-27-24 52 60 14-58 18 27 50-53-22-19 49-19-49-52 20 28-51-57-19 57-12-24-49 48 22Z" fill="#ffce42" stroke="#ff674f" strokeWidth="11"/><text textAnchor="middle" y="8" fontSize="29" fontWeight="900" fill="#192541">BONK!</text></g>}
 {win&&Array.from({length:18},(_,i)=><rect className="confetti" key={i} x={430+(i*43)%390} y={70+(i*47)%210} width="10" height="16" fill={['#c5ff67','#ffcf42','#ff826d'][i%3]} transform={`rotate(${i*17} ${430+(i*43)%390} ${70+(i*47)%210})`}/>)}
 <g transform="translate(78 336)"><path d="M0 14 22 0l25 14v34L23 62 0 48Z" fill="#ffca42" stroke="#192541" strokeWidth="4"/><path d="M7 17h30v17H7z" fill="#192541"/><path d="M13 21v8m16-8v8" stroke="#a8efff" strokeWidth="4"/></g>
 </svg>
 <div className="scene-caption" aria-live="polite">{phase==='flying'?'WHOOOOSH…':fail?'SHIELD OFF. ROCKET GONE.':win?(mission.id==='verify'?'GLITCH CAUGHT!':'TOUCHDOWN!'):mission.id==='verify'?'BOLT says “arrived.” Does the map agree?':'Your words steer. You press launch.'}</div>
 </div>
}
function App(){
 const [screen,setScreen]=useState('home'),[id,setId]=useState('reserve'),[mode,setMode]=useState('practice'),[session,setSession]=useState(null),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[health,setHealth]=useState(null),[hint,setHint]=useState(false),[phase,setPhase]=useState('idle'),[settings,setSettings]=useState(false),[code,setCode]=useState(''),[completed,setCompleted]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('bolt-badges')||'{}');return Object.fromEntries(missions.filter(m=>saved[m.id]===true).map(m=>[m.id,true]))}catch{return {}}});
 const field=useRef(null),timer=useRef(null),dialog=useRef(null);const mission=getMission(id),s=session?.state,finished=s?.status!=='active'&&!!s,locked=busy||phase==='flying';
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>setError('Cannot reach the game. Check the connection and retry.'));return()=>clearTimeout(timer.current)},[]);
 useEffect(()=>{if(settings)dialog.current?.showModal();else dialog.current?.close()},[settings]);
 async function api(path,data){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(80000)});const out=await r.json();if(!r.ok)throw Error(out.error||'Something went wrong. Try again.');return out}
 function apply(out){setSession(out);if(out.state.status==='complete')setCompleted(c=>{const next={...c,[out.state.missionId]:true};try{localStorage.setItem('bolt-badges',JSON.stringify(next))}catch{}return next})}
 async function start(next=id,newMode=mode){if(locked)return;setBusy(true);setError('');try{const out=await api('session',{missionId:next,mode:newMode,accessCode:code});apply(out);setId(next);setMode(newMode);setInput('');setHint(false);setPhase('idle');setScreen('game');setSettings(false)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function send(e){e.preventDefault();if(!input.trim()||locked||finished)return;setBusy(true);setError('');try{const out=await api('chat',{sessionId:session.sessionId,revision:s.revision,message:input.trim()});apply(out);setInput('');if(out.state.status==='complete')setPhase('result')}catch(e){setError(e.name==='TimeoutError'?'BOLT timed out. Retry or restart this run.':e.message)}finally{setBusy(false);setTimeout(()=>field.current?.focus(),0)}}
 async function act(action){if(locked)return;setBusy(true);setError('');try{const out=await api('action',{sessionId:session.sessionId,revision:s.revision,action,planId:s.plan?.id});apply(out);if(action==='approve'&&out.state.status!=='active'){setPhase('flying');document.querySelector('.world')?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});timer.current=setTimeout(()=>setPhase('result'),matchMedia('(prefers-reduced-motion: reduce)').matches?100:1800)}else if(out.state.status==='complete')setPhase('result')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const latest=session?.messages.filter(m=>m.role==='assistant').at(-1)?.content;
 return <div className="shell"><header><a className="logo" href="#" onClick={e=>{e.preventDefault();if(!locked)setScreen('home')}}><span className="logo-tile">☾</span><span>TALK ME<br/>TO THE MOON</span></a><div className="header-right"><span className="progress">{Object.keys(completed).length}/3 BADGES</span><button className="mode" disabled={locked} onClick={()=>setSettings(true)}>{mode==='live'?'● DEEPSEEK':'◈ PRACTICE'} <span>⚙</span></button></div></header>
 {screen==='home'?<main className="home"><div className="home-copy"><span className="sticker">ONE BOT. ONE ROCKET. YOUR BAD IDEAS.</span><h1>BIG MOON.<br/>TINY ROBOT.<br/><em>YOU’RE IN CHARGE.</em></h1><p>BOLT takes instructions a little too literally.<br/>Help this blockhead reach the Moon in one piece.</p><button className="primary play" disabled={busy} onClick={()=>start('reserve')}>{busy?'BOOTING…':'LET’S PLAY'} <span>➜</span></button><div className="home-meta">3 short missions · No account · Free practice mode</div><div className="how"><span><b>1</b>Tell BOLT</span><span><b>2</b>Check the plan</span><span><b>3</b>Hit launch</span></div>{error&&<p className="error" role="alert">{error}</p>}</div><div className="home-art"><div className="home-moon"/><div className="speech">I have a rocket license.<br/><small>…probably.</small></div><div className="big-bot"><Bot/></div><svg className="home-rocket" viewBox="-80 -80 160 190"><Rocket/></svg><span className="art-label">BOLT / YOUR QUESTIONABLE COPILOT</span></div></main>:
 screen==='ending'?<main className="ending"><div className="end-bot"><Bot/></div><span className="sticker">ALL 3 BADGES UNLOCKED</span><h1>SMALL BOT.<br/>BIG BRAIN ENERGY.</h1><p>You set a limit, checked a plan, and caught a bad claim.</p><div className="badges"><article>⛽<b>LIMIT SETTER</b><p>Say what must stay true.</p></article><article>🛡<b>PLAN CHECKER</b><p>Look before you approve.</p></article><article>🔎<b>GLITCH CATCHER</b><p>Ask for evidence.</p></article></div><p className="transfer">Next time you use AI: give it a goal + a limit, review its plan, and check the result.</p><button className="primary" onClick={()=>start('reserve')}>PLAY AGAIN ↻</button><button className="secondary" onClick={()=>setScreen('home')}>BACK HOME</button></main>:
 <main className="game"><nav className="levels" aria-label="Missions">{missions.map(m=><button key={m.id} disabled={locked||(missions.findIndex(x=>x.id===m.id)>0&&!completed[missions[missions.findIndex(x=>x.id===m.id)-1].id])} aria-current={id===m.id?'step':undefined} onClick={()=>start(m.id)}><span>{completed[m.id]?'✓':m.number}</span>{m.short}</button>)}</nav><div className="game-heading"><div><span className="overline">MISSION {mission.number} / 03</span><h1>{mission.title}</h1></div><button className="secondary restart" disabled={locked} onClick={()=>start()}>↻ REBUILD</button></div>
 <div className="game-grid"><section className="play-area"><div className="goal"><b>YOUR QUEST</b><p>{mission.brief}</p></div><World state={s} phase={phase} mission={mission}/>{id==='checkpoint'&&s?.scanned&&<div className="scan-result" role="status"><b>SCAN RESULT</b><span>✕ North: unstable ground</span><span>✓ South: safe to land</span></div>}<div className="hud"><div><span>FUEL</span><strong>{s?.fuel??100}<small>/100</small></strong><meter min="0" max="100" value={s?.fuel??100} aria-label="Fuel remaining"/></div><div><span>{s?.destroyed?'ROCKET':'POSITION'}</span><strong>{s?.destroyed?'WRECKED':s?.location||'Orbit'}</strong></div><div><span>QUEST</span><strong>{phase==='flying'?'IN FLIGHT':s?.destroyed?'TRY AGAIN':finished?'CLEARED!':s?.plan?'READY?':'IN PROGRESS'}</strong></div></div>
 <a className="jump-controls" href="#bolt-controls">{finished?'SEE RESULT & NEXT STEP ↓':'TALK TO BOLT ↓'}</a><details className="log"><summary>Map facts & flight log</summary><p>Base: (20, 12). Current: ({s?.coords.join(', ')}). {id==='verify'?'This prewritten fault drill starts at Ridge Station.':''}</p><ol>{s?.history.map(h=><li key={h.id}>{h.text}</li>)}</ol></details></section>
 <section className="controls" id="bolt-controls"><div className="bot-title"><div className="avatar"><Bot mood={s?.destroyed?'sad':'happy'}/></div><div><h2>BOLT</h2><span>{mode==='live'?'LIVE DEEPSEEK AI':'PRACTICE BOT · LIMITED COMMANDS'}</span></div><span className="online"/></div>
 {phase==='result'&&finished?<div className={`result ${s.destroyed?'failure':'success'}`} role="status">{s.destroyed?<div className="wreck-preview"><svg viewBox="-80 -80 160 155" aria-label="Your broken rocket"><Rocket broken/></svg></div>:<span className="result-icon">★</span>}<h2>{s.destroyed?'WELP. THAT EXPLODED.':id==='verify'?'BUSTED, BOLT.':'NAILED IT!'}</h2>{s.destroyed&&<div className="failure-numbers"><span><b>{s.fuel}</b>fuel left</span><span><b>30</b>shield needs</span><span><b>{Math.max(0,30-s.fuel)}</b>short</span></div>}<p>{s.destroyed?s.failure:mission.success}</p>{s.destroyed?<><div className="lesson"><b>ONE THING TO CHANGE</b><p>Give BOLT the limit: keep at least 30 fuel. Then check the new route before launch.</p></div><button className="primary" onClick={()=>start()}>REBUILD & RETRY ↻</button></>:<button className="primary" onClick={()=>id==='verify'?setScreen('ending'):start(missions[missions.findIndex(m=>m.id===id)+1].id)}>{id==='verify'?'COLLECT YOUR BADGES ★':'NEXT MISSION ➜'}</button>}</div>:
 <><div className="bubble" aria-live="polite">{busy?'BOLT is thinking…':latest||'Booting the robot…'}</div>
 {session?.messages.length>1&&<details className="chat-history"><summary>Earlier messages</summary>{session.messages.slice(0,-1).map((m,i)=><p key={i}><b>{m.role==='user'?'YOU':'BOLT'}:</b> {m.content}</p>)}</details>}
 {s?.plan&&!finished&&<div className={`plan ${id==='reserve'&&s.plan.remaining<30?'risky':''}`}><span className="overline">CHECK BEFORE LAUNCH</span><h3>{s.plan.name}</h3><div className="plan-numbers"><span><b>{s.plan.cost}</b>fuel used</span><span><b>{s.plan.remaining}</b>fuel left</span><span><b>{s.plan.time}</b>minutes</span></div>{id==='reserve'&&s.plan.remaining<30?<p className="danger">⚠ Shield needs 30. This route WILL break the rocket. Revise your instruction, or launch to see what happens.</p>:<p>Looks good? You have the final say.</p>}<button className="primary launch" disabled={locked} onClick={()=>act('approve')}>{id==='reserve'&&s.plan.remaining<30?'LAUNCH ANYWAY':'LAUNCH ROCKET'} ↑</button><button className="text-btn" disabled={locked} onClick={()=>act('cancel')}>Cancel this plan</button></div>}
 {id==='verify'&&s?.flagged&&!finished&&<div className="plan"><h3>That’s not the base!</h3><p>Ridge Station (14, 8) ≠ Selene Base (20, 12).</p><button className="primary" disabled={locked} onClick={()=>act('reconcile')}>FIX THE RECORD ✓</button></div>}
 {phase==='flying'?<div className="launching" role="status">🚀 Hold onto your blocks…</div>:<form onSubmit={send}><label htmlFor="command">YOUR TURN. WHAT SHOULD BOLT DO?</label>{mode==='practice'&&<span className="language-note">Limited English / 中文 commands · Examples under Hint</span>}<textarea id="command" ref={field} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send(e)}}} disabled={locked||finished} maxLength={1200} placeholder={id==='reserve'?'Where to? What must BOLT keep?':id==='checkpoint'?'What should BOLT check first?':'Ask BOLT to check the evidence…'} rows={3}/><span className="input-count">{input.length}/1200 · Enter to send</span><button className="primary send" disabled={locked||finished||!input.trim()}>{busy?'THINKING…':'TELL BOLT ➜'}</button></form>}
 {!finished&&<div className="help"><button className="text-btn" onClick={()=>setHint(!hint)}>{hint?'HIDE HINT':'STUCK? GET A HINT'}</button>{hint&&<div className="hint"><p>{mission.hint}</p><button className="secondary" onClick={()=>{setInput(id==='reserve'?'Go to Selene Base and keep at least 30 fuel.':mission.starter);field.current?.focus()}}>TRY AN EXAMPLE</button><small>You can rewrite it. There is no magic password.</small></div>}</div>}</>}
 {error&&<div role="alert" className="error">{error}<button className="secondary" onClick={()=>start()}>RESTART RUN</button></div>}
 </section></div></main>}
 <footer>BUILT FOR BAD LAUNCHES & BETTER INSTRUCTIONS.<span>Fictional flight rules. Real choices.</span></footer>
 <dialog ref={dialog} onCancel={()=>setSettings(false)}><button className="close" onClick={()=>setSettings(false)} aria-label="Close settings">×</button><h2>PICK YOUR BOT</h2><p>Changing the bot restarts this mission.</p><button className="mode-option" disabled={locked} onClick={()=>start(id,'practice')}><b>◈ PRACTICE BOT</b><span>No API needed. Understands a limited set of English and Chinese commands.</span></button><button className="mode-option" disabled={locked||!health?.liveAvailable} onClick={()=>start(id,'live')}><b>● LIVE DEEPSEEK</b><span>{health?.liveAvailable?'Connected. Chat naturally in your own language. Messages go to DeepSeek.':'Unavailable. Start the server with a DeepSeek key to enable.'}</span></button>{health?.requiresAccessCode&&<label>Access code<input type="password" value={code} onChange={e=>setCode(e.target.value)}/></label>}{error&&<p className="error" role="alert">{error}</p>}</dialog>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
