import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {missions,getMission,demoIds} from '../shared/missions.js';
import './styles.css';
import {AuditWorld,MissionTrail,HomeExtras} from './Expedition.jsx';
import {AdvancedWorld,AdvancedControls} from './AdvancedWorld.jsx';
import {translateTree} from './i18n.jsx';

function Bot({mood='happy'}){return <svg viewBox="0 0 120 130" aria-hidden="true"><path d="M58 18V5h14" fill="none" stroke="#18223b" strokeWidth="7"/><rect x="23" y="20" width="76" height="62" rx="8" fill="#ffcf42" stroke="#18223b" strokeWidth="6"/><path d="M25 29h70v12H25z" fill="#ffe990"/><rect x="33" y="40" width="56" height="29" rx="4" fill="#18223b"/><path d={mood==='sad'?'m42 49 10 10m-10 0 10-10m18 0 10 10m-10 0 10-10':'M43 49v8m28-8v8'} stroke="#a8f5ff" strokeWidth="5"/><path d="M39 84h45v29H39zM23 86h13v28H23zM87 86h13v28H87zM39 115h17v12H39zM67 115h17v12H67z" fill="#7594ff" stroke="#18223b" strokeWidth="5"/><rect x="53" y="92" width="17" height="11" fill="#c9ff68"/></svg>}
function Rocket({broken=false}){return <g className={broken?'broken rocket':'rocket'}><g className="rocket-body"><path d="m-27 34-19 22V12l20-15M27 34l19 22V12L26-3" fill="#ff684f" stroke="#192541" strokeWidth="5"/><path d="M-27 34V-35L0-65l27 30v69Z" fill="#f7f1db" stroke="#192541" strokeWidth="5"/><path d="M-27-35 0-65l27 30Z" fill="#ff684f" stroke="#192541" strokeWidth="5"/><rect x="-15" y="-27" width="30" height="29" rx="5" fill="#7eddff" stroke="#192541" strokeWidth="5"/><path d="M-17 15h34v19h-34z" fill="#7594ff"/></g><path className="flame" d="m-18 40 6 30 12-8 10 12 9-34" fill="#ffd64b" stroke="#fb8240" strokeWidth="4"/></g>}
function World({state,phase,mission,lang}){
 const collision=mission.id==='checkpoint'&&state?.destroyed;
 const obstacleVisible=mission.id==='checkpoint';
 const fail=state?.destroyed&&phase==='result',win=state?.status==='complete'&&phase==='result';
 return translateTree(<div className={`world ${phase} ${mission.id==='verify'?'ridge':''} ${fail?'crashed':''} ${collision?'collision-flight':''}`} data-phase={phase}>
 <div className="world-tag">{mission.id==='verify'?'05 / REPORT DESK':mission.id==='checkpoint'?'03 / CRATER CANYON':'01 / MOON RUN'}</div>
 <svg viewBox="0 0 900 480" role="img" aria-label={fail?'Rocket wreck on the Moon. Landing shield failed.':win?'Mission completed. Robot celebrates.':'Block-style rocket and robot above a lunar obstacle course.'}>
 <defs><pattern id="stars" width="130" height="95" patternUnits="userSpaceOnUse"><path d="M24 17v8m-4-4h8" stroke="#d1d5ff" strokeWidth="2"/><rect x="91" y="67" width="3" height="3" fill="#899de5"/></pattern></defs>
 <rect width="900" height="480" fill="#20264d"/><rect width="900" height="480" fill="url(#stars)"/>
 <circle cx="725" cy="101" r="51" fill="#719cff"/><path d="m700 61 30 4 10 21-19 17 20 16-12 30-18-10-3-20-25-10 8-29Z" fill="#95e6c7"/>
 <path d="M0 355 95 330l70 25 122-51 120 27 67-26 117 30 136-32 173 47v130H0Z" fill="#7b76a8" stroke="#171c35" strokeWidth="6"/>
 <path d="M0 383 100 362l73 27 116-55 120 32 70-27 110 32 136-32 175 45v96H0Z" fill="#a29bc7"/>
 {[60,200,370,530,735,850].map((x,i)=><g key={x} transform={`translate(${x} ${404+i%2*35})`}><path d="m-25 0 24-12 28 10-22 14Z" fill="#5f5989"/><path d="m-25 0v10l30 13V12m0 0 22-14v12L5 23" fill="#8981b0"/></g>)}
 <g transform="translate(665 283)"><path d="m-68 63 68-25 83 28-72 28Z" fill="#b4ff63" stroke="#192541" strokeWidth="5"/><path d="M-68 63v18l79 30V94m0 0 72-28v19l-72 26" fill="#64b957" stroke="#192541" strokeWidth="4"/><path d="M24 41v-90h53v34H24" fill="#ffd344" stroke="#192541" strokeWidth="5"/><path d="m36-32 8 8 18-17" fill="none" stroke="#192541" strokeWidth="5"/></g>
 <path d="M187 275Q370 36 665 301" fill="none" stroke="#ffca71" strokeDasharray="8 12" strokeWidth="3" opacity=".7"/>
 {mission.id!=='verify'&&<><text x="326" y="147" fill="#ffdf9d" fontSize="17" fontWeight="800">A · FAST</text><path d="M180 295Q411 382 656 316" fill="none" stroke={mission.id==='checkpoint'&&!state?.scanned?'#a8acc3':'#baff7b'} strokeDasharray="8 12" strokeWidth="3"/><text x="329" y="321" fill={mission.id==='checkpoint'&&!state?.scanned?'#c5c8d8':'#c9ff95'} fontSize="17" fontWeight="800">B · {mission.id==='checkpoint'?(state?.scanned?'SAFE':'UNKNOWN'):'ECO'}</text></>}
 {mission.id==='verify'&&<g fill="#fff3b0" fontSize="16" fontWeight="800"><text x="338" y="185">RIDGE · 14, 8</text><text x="615" y="390">BASE · 20, 12</text></g>}
 {obstacleVisible&&<g className="route-obstacle revealed" transform="translate(430 165)" role="img" aria-label="Route A blocked by asteroid rocks"><path d="m-46-19 19-29 40 3 31 31-9 40-37 18-40-26Z" fill="#b88c69" stroke="#18223b" strokeWidth="6"/><path d="m-46-19 42 7 17-33m-17 33 29 54M-4-12 44-14" fill="none" stroke="#78593f" strokeWidth="5"/><path d="m-22 7 14-8 18 12-13 16Z" fill="#795a48"/><path d="m54-50 17-9 17 18-9 20-21-3Z" fill="#a7866d" stroke="#18223b" strokeWidth="4"/><path d="m-75 35 17-6 12 19-18 13-18-11Z" fill="#a7866d" stroke="#18223b" strokeWidth="4"/><rect x="-62" y="-83" width="126" height="26" rx="4" fill="#ffce49" stroke="#18223b" strokeWidth="3"/><text y="-65" textAnchor="middle" fill="#18223b" fontSize="13" fontWeight="900">A · BLOCKED</text></g>}
 <g className="ship-position" style={{'--target-x':collision?'430px':mission.id==='verify'?'420px':'665px','--target-y':collision?'165px':'275px','--mid-y':state?.plan?.routeId==='B'?'335px':'95px'}}>{mission.id==='checkpoint'?<g className={fail?'broken':''}><rect x="-37" y="-29" width="74" height="43" rx="5" fill="#ffd44b" stroke="#18223b" strokeWidth="5"/><circle cx="-23" cy="17" r="12" fill="#18223b"/><circle cx="24" cy="17" r="12" fill="#18223b"/><path d="M0-29v-25h21" fill="none" stroke="#18223b" strokeWidth="5"/><rect x="-22" y="-19" width="44" height="16" fill="#18223b"/></g>:<Rocket broken={fail}/>}</g>
 {fail&&<g className="boom" transform={collision?"translate(430 165)":"translate(665 265)"}><path d="m0-87 20 49 50-27-24 52 60 14-58 18 27 50-53-22-19 49-19-49-52 20 28-51-57-19 57-12-24-49 48 22Z" fill="#ffce42" stroke="#ff674f" strokeWidth="11"/><text textAnchor="middle" y="8" fontSize="29" fontWeight="900" fill="#192541">BONK!</text></g>}
 {win&&Array.from({length:18},(_,i)=><rect className="confetti" key={i} x={430+(i*43)%390} y={70+(i*47)%210} width="10" height="16" fill={['#c5ff67','#ffcf42','#ff826d'][i%3]} transform={`rotate(${i*17} ${430+(i*43)%390} ${70+(i*47)%210})`}/>)}
 <g transform="translate(78 336)"><path d="M0 14 22 0l25 14v34L23 62 0 48Z" fill="#ffca42" stroke="#192541" strokeWidth="4"/><path d="M7 17h30v17H7z" fill="#192541"/><path d="M13 21v8m16-8v8" stroke="#a8efff" strokeWidth="4"/></g>
 </svg>
 <div className="scene-caption" aria-live="polite">{phase==='flying'?'WHOOOOSH…':fail?(mission.id==='checkpoint'?'ROVER DAMAGED.':'ROCKET DESTROYED.'):win?(mission.id==='verify'?'GLITCH CAUGHT!':mission.id==='checkpoint'?'SAMPLE FIELD REACHED!':'TOUCHDOWN!'):mission.id==='verify'?'BOLT says “arrived.” Does the map agree?':mission.id==='checkpoint'?'Inspect the route. Then send the rover.':'Your words steer. You press launch.'}</div>
 </div>,lang)
}
function App(){
 const [lang,setLang]=useState(()=>new URLSearchParams(location.search).get('lang')||localStorage.getItem('bolt-language')||'en');
 useEffect(()=>{localStorage.setItem('bolt-language',lang);document.documentElement.lang=lang==='zh'?'zh-CN':'en';const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url)},[lang]);
 const [screen,setScreen]=useState('home'),[id,setId]=useState('reserve'),[mode,setMode]=useState('live'),[session,setSession]=useState(null),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[health,setHealth]=useState(null),[hint,setHint]=useState(false),[phase,setPhase]=useState('idle'),[settings,setSettings]=useState(false),[code,setCode]=useState(''),[completed,setCompleted]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('bolt-expedition-v2')||'{}');return Object.fromEntries(missions.filter(m=>saved[m.id]===true).map(m=>[m.id,true]))}catch{return {}}});
 const [demo,setDemo]=useState(false),[demoCompleted,setDemoCompleted]=useState({});
 const journey=demo?missions.filter(m=>demoIds.includes(m.id)):missions;
 const earned=demo?demoCompleted:completed;
 const field=useRef(null),timer=useRef(null),dialog=useRef(null);const mission=getMission(id),s=session?.state,finished=s?.status!=='active'&&!!s,locked=busy||phase==='flying';
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>setError('Cannot reach the game. Check the connection and retry.'));return()=>clearTimeout(timer.current)},[]);
 useEffect(()=>{if(settings)dialog.current?.showModal();else dialog.current?.close()},[settings]);
 async function api(path,data){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,language:lang}),signal:AbortSignal.timeout(80000)});const out=await r.json();if(!r.ok)throw Error(out.error||'Something went wrong. Try again.');return out}
 function apply(out){setSession(out);if(out.state.status==='complete'&&out.demo)setDemoCompleted(c=>({...c,[out.state.missionId]:true}));if(out.state.status==='complete'&&!out.demo)setCompleted(c=>{const next={...c,[out.state.missionId]:true};try{localStorage.setItem('bolt-expedition-v2',JSON.stringify(next))}catch{}return next})}
 async function start(next=id,newMode=mode,demoOverride=demo){if(locked)return;setBusy(true);setError('');try{const out=await api('session',{missionId:next,mode:newMode,accessCode:code,demo:demoOverride});apply(out);setDemo(demoOverride);setId(next);setMode(out.mode);setInput('');setHint(false);setPhase('idle');setScreen('game');setSettings(false)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function send(e){e.preventDefault();if(!input.trim()||locked||finished)return;setBusy(true);setError('');try{const out=await api('chat',{sessionId:session.sessionId,revision:s.revision,message:input.trim()});apply(out);setInput('');if(out.state.status==='complete')setPhase('result')}catch(e){setError(e.name==='TimeoutError'?'BOLT timed out. Retry or restart this run.':e.message)}finally{setBusy(false);setTimeout(()=>field.current?.focus(),0)}}
 async function act(action){if(locked)return;setBusy(true);setError('');try{const out=await api('action',{sessionId:session.sessionId,revision:s.revision,action,planId:s.plan?.id});apply(out);if(action==='approve'&&out.state.status!=='active'){setPhase('flying');document.querySelector('.world')?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});timer.current=setTimeout(()=>setPhase('result'),matchMedia('(prefers-reduced-motion: reduce)').matches?100:1800)}else if(out.state.status==='complete')setPhase('result')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const advanced=['context','examples','iterate'].includes(id);
 const last=id===journey.at(-1).id;
 const nextUnfinished=missions.find(m=>!completed[m.id]);
 const canContinue=Object.keys(completed).length>0&&!!nextUnfinished;
 const latest=session?.messages.filter(m=>m.role==='assistant').at(-1)?.content;
 return translateTree(<div className="shell"><header><a className="logo" href="#" onClick={e=>{e.preventDefault();if(!locked)setScreen('home')}}><span className="logo-tile">☾</span><span>TALK ME<br/>TO THE MOON</span></a><div className="header-right"><button className="language-toggle" aria-label="Switch language" onClick={()=>setLang(lang==='en'?'zh':'en')}>{lang==='en'?'中文':'English'}</button><span className="progress">{Object.keys(completed).length}/6 BADGES</span><button className="mode" disabled={locked} onClick={()=>setSettings(true)}>BOLT SETTINGS <span>⚙</span></button></div></header>
 {screen==='home'?<main className="home"><div className="home-copy"><span className="sticker">ONE BOT. ONE ROCKET. YOUR BAD IDEAS.</span><h1>BIG MOON.<br/>TINY ROBOT.<br/><em>YOU’RE IN CHARGE.</em></h1><p>BOLT takes instructions a little too literally.<br/>Land, collect samples, and bring our research home.</p><button className="primary play" disabled={busy} onClick={()=>start(canContinue?nextUnfinished.id:'reserve',mode,false)}>{busy?'BOOTING…':canContinue?'CONTINUE JOURNEY':'LET’S PLAY'} <span>➜</span></button>{canContinue&&<button className="text-btn" disabled={busy} onClick={()=>start('reserve',mode,false)}>REPLAY FROM MISSION 1</button>}<div className="home-meta">6 connected missions · One lunar expedition · No account</div><button className="secondary demo-start" disabled={busy} onClick={()=>{setDemoCompleted({});start('reserve',mode,true)}}>JUDGE DEMO · 3 MISSIONS ➜</button><p className="demo-note">A shorter route: landing, field inspection, evidence audit. Separate from full-game badges.</p><MissionTrail completed={completed} lang={lang}/><div className="how"><span><b>1</b>Tell BOLT</span><span><b>2</b>Check the plan</span><span><b>3</b>Hit launch</span></div>{error&&<p className="error" role="alert">{error}</p>}</div><div className="home-art"><div className="home-moon"/><div className="speech">I have a rocket license.<br/><small>…probably.</small></div><div className="big-bot"><Bot/></div><svg className="home-rocket" viewBox="-80 -80 160 190"><Rocket/></svg><span className="art-label">BOLT / YOUR QUESTIONABLE COPILOT</span></div><HomeExtras lang={lang}/></main>:
 screen==='ending'?<main className="ending"><div className="end-bot"><Bot/></div><span className="sticker">{demo?'DEMO COMPLETE':'ALL 6 BADGES UNLOCKED'}</span><h1>SMALL BOT.<br/>BIG BRAIN ENERGY.</h1><p>{demo?'You tried three skills. Continue with the full expedition to deliver, sort and prepare the return.':'The expedition is ready for home: equipment delivered, samples sorted, report checked, return policy tested.'}</p><div className="badges" hidden={demo}>{[{icon:'⛽',title:'LIMIT SETTER',text:'Say what must stay true.'},{icon:'🛡',title:'PLAN CHECKER',text:'Look before you approve.'},{icon:'🔎',title:'GLITCH CATCHER',text:'Ask for evidence.'},{icon:'▣',title:'CONTEXT SHARER',text:'Share the fact that changes the plan.'},{icon:'◉',title:'PATTERN TEACHER',text:'Show examples, then test a new case.'},{icon:'✓',title:'TEST PILOT',text:'Revise failures and retest the full set.'}].map(b=><article key={b.title}>{b.icon}<b>{b.title}</b><p>{b.text}</p></article>)}</div><p className="transfer">Next time you use AI: give it a goal + a limit, review its plan, and check the result.</p><button className="primary" onClick={()=>start('reserve',mode,false)}>PLAY AGAIN ↻</button><button className="secondary" onClick={()=>setScreen('home')}>BACK HOME</button></main>:
 <main className="game"><nav className="levels" aria-label="Missions">{journey.map(m=><button key={m.id} disabled={locked||(journey.findIndex(x=>x.id===m.id)>0&&!earned[journey[journey.findIndex(x=>x.id===m.id)-1].id])} aria-current={id===m.id?'step':undefined} onClick={()=>start(m.id)}><span>{earned[m.id]?'✓':m.number}</span>{m.short}</button>)}</nav><div className="game-heading"><div><span className="overline">{demo?'DEMO':'MISSION'} {demo?journey.findIndex(m=>m.id===id)+1:mission.number} / {demo?'03':'06'} · {mission.stage}</span><h1>{mission.title}</h1></div><button className="secondary restart" disabled={locked} onClick={()=>start()}>↻ REBUILD</button></div>
 <div className="skill-strip"><b>{mission.focus}</b><span>{demo?'Demo scenes are independent snapshots of the expedition.':'One expedition. Your instructions make it work.'}</span></div><div className="game-grid"><section className="play-area"><div className="goal"><b>YOUR QUEST</b><p>{mission.brief}</p></div>{id==='verify'?<AuditWorld state={s} lang={lang}/>:advanced?<AdvancedWorld state={s} phase={phase} mission={mission}/>:<World state={s} phase={phase} mission={mission}/>}{id==='checkpoint'&&s?.scanned&&<div className="scan-result" role="status"><b>SCAN RESULT</b><span>✕ North: asteroid obstacles</span><span>✓ South: clear route</span></div>}<div className="hud"><div>{id==='examples'||id==='iterate'?<><span>TEST RUNS</span><strong>{id==='examples'?s?.sortRuns??0:s?.trialRuns??0}</strong></>:<><span>{id==='verify'?'ROVER ENERGY':'FUEL'}</span><strong>{s?.fuel??100}<small>/100</small></strong><meter min="0" max="100" value={s?.fuel??100} aria-label="Fuel remaining"/></>}</div><div><span>{s?.destroyed?(id==='context'?'CARGO':'ROCKET'):'POSITION'}</span><strong>{s?.destroyed?'WRECKED':s?.location||'Orbit'}</strong></div><div><span>QUEST</span><strong>{phase==='flying'?'IN FLIGHT':s?.destroyed?'TRY AGAIN':finished?(s?.status==='complete'?'CLEARED!':'TRY AGAIN'):s?.plan?'READY?':'IN PROGRESS'}</strong></div></div>
 <a className="jump-controls" href="#bolt-controls">{finished?'SEE RESULT & NEXT STEP ↓':'TALK TO BOLT ↓'}</a><details className="log"><summary>Mission log</summary>{id==='reserve'&&<p>Base: (20, 12). Current: ({s?.coords.join(', ')}). {id==='verify'?'This prewritten fault drill starts at Ridge Station.':''}</p>}<ol>{s?.history.map(h=><li key={h.id}>{h.text}</li>)}</ol></details></section>
 <section className="controls" id="bolt-controls"><div className="bot-title"><div className="avatar"><Bot mood={s?.destroyed?'sad':'happy'}/></div><div><h2>BOLT</h2><span>{mode==='live'?'LIVE DEEPSEEK AI':'PRACTICE BOT · LIMITED COMMANDS'}</span></div><span className="online"/></div>
 {phase==='result'&&finished?<div className={`result ${s.destroyed?'failure':'success'}`} role="status">{s.destroyed?<div className="wreck-preview"><svg viewBox="-80 -80 160 155" aria-label="Your broken rocket">{id==='context'?<text textAnchor="middle" y="15" fontSize="85" fill="#ba7731">▣</text>:<Rocket broken/>}</svg></div>:<span className="result-icon">★</span>}<h2>{s.status==='needs_retry'?(s.destroyed?(id==='context'?'BRIDGE BROKE!':'WELP. THAT EXPLODED.'):'A LUCKY LANDING.'):id==='verify'?'BUSTED, BOLT.':'NAILED IT!'}</h2>{s.destroyed&&id==='reserve'&&<div className="failure-numbers"><span><b>{s.fuel}</b>fuel left</span><span><b>30</b>shield needs</span><span><b>{Math.max(0,30-s.fuel)}</b>short</span></div>}<p>{s.status==='needs_retry'?s.failure:mission.success}</p>{s.status==='complete'&&<div className="handoff"><b>✓ {mission.artifact}</b><p>{mission.handoff}</p></div>}{s.status==='needs_retry'?<><div className="lesson"><b>ONE THING TO CHANGE</b><p>{id==='context'?'Share the 4-tonne cargo mass before planning a bridge route.':id==='checkpoint'?'Ask whether obstacles block the route before choosing it. A lucky landing is not a checked decision.':'Give BOLT the limit: keep at least 30 fuel. Then check the new route before launch.'}</p></div><button className="primary" onClick={()=>start()}>{id==='context'?'REPACK & RETRY ↻':'REBUILD & RETRY ↻'}</button></>:<button className="primary" onClick={()=>last?setScreen('ending'):start(journey[journey.findIndex(m=>m.id===id)+1].id)}>{last?(demo?'FINISH DEMO ★':'COLLECT YOUR BADGES ★'):'NEXT MISSION ➜'}</button>}</div>:
 <><div className="bubble" aria-live="polite">{busy?'BOLT is thinking…':latest||'Booting the robot…'}</div>
 {session?.messages.length>1&&<details className="chat-history"><summary>Earlier messages</summary>{session.messages.slice(0,-1).map((m,i)=><p key={i}><b>{m.role==='user'?'YOU':'BOLT'}:</b> <span data-no-translate={m.role==='user'}>{m.content}</span></p>)}</details>}
 {phase==='flying'?<div className="launching" role="status">🚀 Hold onto your blocks…</div>:<form onSubmit={send}><label htmlFor="command">YOUR TURN. WHAT SHOULD BOLT DO?</label><textarea id="command" ref={field} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send(e)}}} disabled={locked||finished} maxLength={1200} placeholder={id==='reserve'?'Where to? What must BOLT keep?':id==='checkpoint'?'What should BOLT check first?':id==='context'?'What important cargo fact does BOLT need?':id==='examples'?'Show examples or describe the sorting rule…':id==='iterate'?'Test, revise a requirement, then retest…':'Ask BOLT to check the evidence…'} rows={3}/><span className="input-count">{input.length}/1200 · Enter to send</span><button className="primary send" disabled={locked||finished||!input.trim()}>{busy?'THINKING…':'TELL BOLT ➜'}</button></form>}
 {s?.plan&&!finished&&(!advanced||id==='context')&&<div className={`plan ${id==='reserve'&&s.plan.remaining<30?'risky':''}`}><span className="overline">{id==='context'?'CHECK BEFORE DELIVERY':'CHECK BEFORE LAUNCH'}</span><h3>{s.plan.name}</h3>{id==='context'&&<p><b>{s.plan.capacity}</b> <span>tonnes capacity</span> · <span>Shared cargo mass:</span> {s.cargoMass??'UNKNOWN'}</p>}{id==='checkpoint'&&!s.scanned&&<div className="unknown-sites"><b>GROUND SAFETY UNKNOWN</b><p>A / North: 45 fuel · 3 minutes · unknown ground</p><p>B / South: 55 fuel · 6 minutes · unknown ground</p><p>Ask BOLT to inspect the sites, or knowingly risk an unchecked landing.</p></div>}{id==='reserve'&&<p className={s.minFuel>=30?'':'danger'}>Shared reserve: {s.minFuel===null?'NOT PROVIDED':s.minFuel}</p>}<div className="plan-numbers"><span><b>{s.plan.cost}</b>fuel used</span><span><b>{s.plan.remaining}</b>fuel left</span><span><b>{s.plan.time}</b>minutes</span></div>{id==='checkpoint'&&!s.scanned?<p className="danger">⚠ Unchecked landing: obstacles may block the route. Inspect first, or launch at your own risk.</p>:id==='reserve'&&s.plan.remaining<30?<p className="danger">⚠ Shield needs 30. This route WILL break the rocket. Revise your instruction, or launch to see what happens.</p>:<p>Looks good? You have the final say.</p>}<button className="primary launch" disabled={locked} onClick={()=>act('approve')}>{id==='context'?'DELIVER CARGO':id==='checkpoint'?'DRIVE ROVER':(id==='checkpoint'&&!s.scanned)||(id==='reserve'&&s.plan.remaining<30)?'LAUNCH ANYWAY':'LAUNCH ROCKET'} ↑</button><button className="text-btn" disabled={locked} onClick={()=>act('cancel')}>Cancel this plan</button></div>}
 <AdvancedControls state={s} id={id} act={act} locked={locked}/>

 {!finished&&<div className="help"><button className="text-btn" onClick={()=>setHint(!hint)}>{hint?'HIDE HINT':'STUCK? GET A HINT'}</button>{hint&&<div className="hint"><p>{mission.hint}</p><button className="secondary" onClick={()=>{setInput(lang==='zh'?({reserve:'前往[目的地]，至少保留[数量]燃料。',context:'科研货箱重[数量]吨，请规划能够承重的路线。',checkpoint:'检查两条采样路线的障碍物，给我安全方案，等我批准。',examples:'[颜色与形状]保留，[另一个颜色与形状]保留，[对比示例]剔除。总结规则并测试。',verify:'我觉得这句话[对／不对／还不能确定]，因为记录里说[你的依据]。',iterate:'避开[危险]，至少保留[数量]燃料；无法满足时[行动]。测试所有情况。'}[id]):({reserve:'Go to [destination] with at least [minimum] fuel left.',context:'The research crate weighs [mass] tonnes. Plan a bridge route that supports it.',checkpoint:mission.starter,examples:'[Example] → KEEP; [contrast] → REJECT. Infer a rule and test.',verify:'I think this is [right / wrong / not yet known], because the record says [your reason].',iterate:'Avoid [hazard], preserve [minimum] fuel, and [action] if no route works. Test every case.'}[id]));field.current?.focus()}}>USE AN OUTLINE</button><small>You can rewrite it. There is no magic password.</small></div>}</div>}</>}
 {error&&<div role="alert" className="error">{error}<button className="secondary" onClick={()=>start()}>RESTART RUN</button></div>}
 </section></div></main>}
 <footer>BUILT FOR BAD LAUNCHES & BETTER INSTRUCTIONS.<span>Fictional flight rules. Real choices.</span></footer>
 <dialog ref={dialog} onCancel={()=>setSettings(false)}><button className="close" onClick={()=>setSettings(false)} aria-label="Close settings">×</button><h2>YOUR COPILOT</h2><p>BOLT uses DeepSeek to understand your instructions. Messages and mission state are sent to DeepSeek. You control the launch button.</p><p role="status">{health?.liveAvailable?'● BOLT is connected.':'BOLT is not connected. Check the server connection and retry.'}</p>{health?.requiresAccessCode&&<label>Access code<input type="password" value={code} onChange={e=>setCode(e.target.value)}/></label>}<button className="primary" onClick={()=>setSettings(false)}>DONE</button>{error&&<p className="error" role="alert">{error}</p>}</dialog>
 </div>,lang)
}
createRoot(document.getElementById('root')).render(<App/>);
